todo: servidor cliente
servidor: servidor_utils.cpp servidor.cpp
	g++ servidor_utils.cpp servidor.cpp -o servidor.exe -lpthread

cliente: cliente_utils.cpp cliente.cpp
	g++ cliente_utils.cpp cliente.cpp -o cliente.exe -lpthread